name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test
    - run: cargo test --no-default-features
    - run: cargo clippy -- -D warnings
    - run: cargo fmt --check
